namePrefix: local-

resources:
- ../../base

patchesStrategicMerge:
  - config-map.yaml

patches:
  - target:
      kind: Deployment
      name: deployment
      version: v1beta1
    path: deployment.yaml
