apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: deployment
    spec:
      containers:
        - name: webservice
          image: monopole/hello:1
          command: ["/hello", "--port=8080"]
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: FOO
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: foo
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
